// Generated by Tools/physics-lab/presets.js — do not edit by hand.
// Regenerate with: node Tools/physics-lab/presets.js --swift
//
// Every constant below is range-checked by that generator against the
// perceptual guard rails documented in Tools/physics-lab/README.md.

import Foundation

extension ScrollPreset {

    /// Short, deliberate steps. Built for code and layout work.
    public static let precise = ScrollPreset(
        id: "precise",
        name: "Precise",
        blurb: "Short, deliberate steps. Built for code and layout work.",
        acceleration: AccelerationCurve(
            minSpeed: 1.0,
            maxSpeed: 24.0,
            minDistance: 28.0,
            maxDistance: 110.0,
            shape: UnitBezier(0.30, 0.00, 0.70, 1.00)
        ),
        friction: 11.5,
        stopThreshold: 8.0,
        momentumEnabled: true
    )

    /// Trackpad-like glide with a firm landing. The default.
    public static let balanced = ScrollPreset(
        id: "balanced",
        name: "Balanced",
        blurb: "Trackpad-like glide with a firm landing. The default.",
        acceleration: AccelerationCurve(
            minSpeed: 1.0,
            maxSpeed: 28.0,
            minDistance: 48.0,
            maxDistance: 220.0,
            shape: UnitBezier(0.35, 0.00, 0.65, 1.00)
        ),
        friction: 6.4,
        stopThreshold: 8.0,
        momentumEnabled: true
    )

    /// Long, low-friction coasting for reading and long documents.
    public static let glide = ScrollPreset(
        id: "glide",
        name: "Glide",
        blurb: "Long, low-friction coasting for reading and long documents.",
        acceleration: AccelerationCurve(
            minSpeed: 1.0,
            maxSpeed: 30.0,
            minDistance: 60.0,
            maxDistance: 300.0,
            shape: UnitBezier(0.25, 0.10, 0.25, 1.00)
        ),
        friction: 3.9,
        stopThreshold: 8.0,
        momentumEnabled: true
    )

    /// No coasting at all. The wheel stops when you do.
    public static let snappy = ScrollPreset(
        id: "snappy",
        name: "Snappy",
        blurb: "No coasting at all. The wheel stops when you do.",
        acceleration: AccelerationCurve(
            minSpeed: 1.0,
            maxSpeed: 26.0,
            minDistance: 52.0,
            maxDistance: 190.0,
            shape: UnitBezier(0.42, 0.00, 0.58, 1.00)
        ),
        friction: 22.0,
        stopThreshold: 12.0,
        momentumEnabled: false
    )

    /// Classic discrete stepping, smoothed but never accelerated.
    public static let lineByLine = ScrollPreset(
        id: "lineByLine",
        name: "Line by Line",
        blurb: "Classic discrete stepping, smoothed but never accelerated.",
        acceleration: AccelerationCurve(
            minSpeed: 1.0,
            maxSpeed: 40.0,
            minDistance: 40.0,
            maxDistance: 40.0,
            shape: UnitBezier(0.00, 0.00, 1.00, 1.00)
        ),
        friction: 30.0,
        stopThreshold: 12.0,
        momentumEnabled: false
    )

    /// Every preset Glide ships with, in the order the UI lists them.
    public static let builtIn: [ScrollPreset] = [
        .precise,
        .balanced,
        .glide,
        .snappy,
        .lineByLine,
    ]

    /// The preset applied to a freshly created profile.
    public static let `default`: ScrollPreset = .balanced
}
